services:

  postgres:
    image: postgres:16
    container_name: qcraque-postgres

    environment:
      POSTGRES_DB: qcraque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  backend:
    build:
      context: ./backend

    container_name: qcraque-backend

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/qcraque

    ports:
      - "8000:8000"

    depends_on:
      - postgres


volumes:
  postgres_data:
